spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.cnodvtkrz1fq.ap-northeast-2.rds.amazonaws.com:3306/library_db?zeroDateTimeBehavior=convertToNull
    username: aws
    password: 1q2w3e4r!!

  mail:
    host: smtp.gmail.com
    port: 465
    username: daynoteblog
    address: daynoteblog@gmail.com
    password: ikymmlkeqthyurju
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true



jwt:
  secret: 9fumyD2mbOBAbmii7+CF8ZhI3fQzmHXIkTE9ByJU4tLhxa15YBl5SkbOwDMx6v4F

